### PR TITLE
Issue 17 support replace object

### PR DESCRIPTION
**Pull request by javierblancosp**
### Description
🎁  Support objects on value replacing
💄  Add ES6

### Related
* https://github.com/datavis-tech/json-templates/issues/17

### CODE REVIEW

**Comment by javierblancosp** [comment]
Jaja okey, sorry for my english :P

**Comment by javierblancosp** [comment]
Done ;), thanks for your time

**Comment by javierblancosp** [comment]
Thanks you for your time, do you know when we will have a release with that?

**Comment by curran** [comment]
https://github.com/datavis-tech/json-templates/releases/tag/v2.0.0

**Pull request merged**
