### PR TITLE
Add support to use $

### PR DESCRIPTION
**Pull request by pranavwani**
Can use `$` as: `{{$ip}}`

### CODE REVIEW

**Comment by curran** [comment]
@pranavwani Apologies, I'm just noticing this now! Would you be able to please add a test that covers this change? Thanks!

**Comment by curran** [comment]
This is good. I will add the test. Thanks for this!

**Comment by pranavwani** [comment]
@curran Thanks :+1:

**Comment by pranavwani** [comment]
> @pranavwani Apologies, I'm just noticing this now! Would you be able to please add a test that covers this change? Thanks!

Sorry, about that. Just seen that the test case is not added

**Comment by curran** [comment]
My pleasure! Thanks for this contribution. 🙏

**Pull request merged**
